services:
  nginx:
    build: ./build/dev/nginx
    ports:
      - '81:80'
    depends_on:
      - api
    networks:
      - backend
  api:
    build:
      context: .
      dockerfile: ./build/dev/Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - redis
    volumes:
      - .:/app
    networks:
      - backend